from ficsit2.com.names import ComponentName, Buildable
from ficsit2.com.machines import Machine

DECIMAL_FORMAT = "{:.5g}"

# List of endpoints that signify no further recipes will be found
ENDPOINTS = [
    ComponentName.RAW_QUARTZ,
    ComponentName.IRON_ORE,
    ComponentName.COPPER_ORE,
    ComponentName.BAUXITE_ORE,
    ComponentName.URANIUM_ORE,
    ComponentName.CATERIUM_ORE,
    ComponentName.COAL,
    ComponentName.SULFUR,
    ComponentName.NITROGEN,
    ComponentName.LIMESTONE,
    ComponentName.WATER,
    ComponentName.OIL,
    ComponentName.LEAVES,
    ComponentName.FLOWER_PETALS,
    ComponentName.WOOD,
    ComponentName.BACON_AGARIC,
    ComponentName.MYCELIA,
    ComponentName.HOG_REMAINS,
    ComponentName.SPITTER_REMAINS,
    ComponentName.STINGER_REMAINS,
    ComponentName.HATCHER_REMAINS,
    ComponentName.PLUTONIUM_WASTE,
]

# List of Components that count as a fluid - mostly for display purposes out of Component
FLUIDS = [
    ComponentName.WATER,
    ComponentName.OIL,
    ComponentName.HEAVY_OIL_RESIDUE,
    ComponentName.FUEL,
    ComponentName.TURBO_FUEL,
    ComponentName.NITROGEN,
    ComponentName.SULFURIC_ACID,
    ComponentName.NITRIC_ACID,
    ComponentName.ALUMINA_SOLUTION,
]


# List of ignored recipes in Build Recipe
IGNORED_RECIPES = [
    # Outdated
    "Biomass (Alien Carapace)",
    "Biomass (Alien Organs)",
    "Beacon",
    "Alternate: Uranium Fuel Unit",
    # Creates infinite loops and doesn't really add anything to the calculations
    "Alternate: Diluted Packaged Fuel",
    "Packaged Fuel",
    "Packaged Liquid Biofuel",
    "Packaged Oil",
    "Packaged Heavy Oil Residue",
    "Packaged Sulfuric Acid",
    "Packaged Turbofuel",
    "Packaged Water",
    # Handled manually in alternate_recipes.json
    "Empty Canister",
    "Packaged Nitric Acid",
    # Not Needed
    "Power Shard (1)",
    "Power Shard (2)",
    "Power Shard (5)",
    # Weapons that are outdated
    "Alternate: Seismic Nobelisk",
    "Rifle Cartridge",
    "Nobelisk",
    "Spiked Rebar",
]

# As this app is about finding the differences between production chains, and these have no alternates, not very useful
FICSMAS_RECIPES = [
    "Candy Cane",
    "Sweet Fireworks",
    "Fancy Fireworks",
    "Sparkly Fireworks",
    "Actual Snow",
    "Snowball",
    "Red FICSMAS Ornament",
    "Blue FICSMAS Ornament",
    "Copper FICSMAS Ornament",
    "Iron FICSMAS Ornament",
    "FICSMAS Ornament Bundle",
    "FICSMAS Bow",
    "FICSMAS Tree Branch",
    "FICSMAS Decoration",
    "FICSMAS Wonder Star",
]


machine_map = {
    Buildable.MINER: Machine(
        name=Buildable.MINER,
        tierRequired=(0.5, 4.1, 8.3),
        powerUse=(5, 12, 30),
        width=6,
        length=14,
        height=18,
        footprint=84,
    ),
    Buildable.SMELTER: Machine(
        name=Buildable.SMELTER,
        tierRequired=0.2,
        powerUse=4,
        width=6,
        length=9,
        height=9,
        footprint=54,
    ),
    Buildable.FOUNDRY: Machine(
        name=Buildable.FOUNDRY,
        tierRequired=3.3,
        powerUse=16,
        width=10,
        length=9,
        height=9,
        footprint=90,
    ),
    Buildable.CONSTRUCTOR: Machine(
        name=Buildable.CONSTRUCTOR,
        powerUse=4,
        footprint=80,
        tierRequired=0.3,
        width=8,
        length=10,
        height=8,
    ),
    Buildable.ASSEMBLER: Machine(
        name=Buildable.ASSEMBLER,
        tierRequired=2.1,
        powerUse=15,
        width=10,
        length=15,
        height=11,
        footprint=150,
    ),
    Buildable.MANUFACTURER: Machine(
        name=Buildable.MANUFACTURER,
        tierRequired=5.2,
        powerUse=55,
        width=18,
        length=19,
        height=12,
        footprint=342,
    ),
    Buildable.REFINERY: Machine(
        name=Buildable.REFINERY,
        tierRequired=5.1,
        powerUse=30,
        width=10,
        length=20,
        height=31,
        footprint=200,
    ),
    Buildable.PACKAGER: Machine(
        name=Buildable.PACKAGER,
        tierRequired=5.3,
        powerUse=10,
        width=8,
        length=8,
        height=12,
        footprint=64,
    ),
    Buildable.BLENDER: Machine(
        name=Buildable.BLENDER,
        tierRequired=7.1,
        powerUse=75,
        width=18,
        length=19,
        height=12,
        footprint=342,
    ),
    Buildable.PARTICLE_ACCELERATOR: Machine(
        name=Buildable.PARTICLE_ACCELERATOR,
        tierRequired=8.4,
        powerUse=1500,
        width=24,
        length=38,
        height=32,
        footprint=912,
    ),
    Buildable.NUCLEAR_POWER_PLANT: Machine(
        name=Buildable.NUCLEAR_POWER_PLANT,
        tierRequired=8.1,
        powerUse=-2500,
        width=38,
        length=43,
        height=49,
        footprint=1634,
    ),
}


MACHINE_MAPPING = {
    "Smelter": machine_map.get(Buildable.SMELTER),
    "Foundry": machine_map.get(Buildable.FOUNDRY),
    "Constructor": machine_map.get(Buildable.CONSTRUCTOR),
    "Assembler": machine_map.get(Buildable.ASSEMBLER),
    "Manufacturer": machine_map.get(Buildable.MANUFACTURER),
    "OilRefinery": machine_map.get(Buildable.REFINERY),
    "Blender": machine_map.get(Buildable.BLENDER),
    "Packager": machine_map.get(Buildable.PACKAGER),
    "HadronCollider": machine_map.get(Buildable.PARTICLE_ACCELERATOR),
}

COMPONENT_MAPPING = {
    "portableMiner": ComponentName.PORTABLE_MINER,
    "goldIngot": ComponentName.CATERIUM_INGOT,
    "steelIngot": ComponentName.STEEL_INGOT,
    "stone": ComponentName.LIMESTONE,
    "oreIron": ComponentName.IRON_ORE,
    "oreCopper": ComponentName.COPPER_ORE,
    "rawQuartz": ComponentName.RAW_QUARTZ,
    "coal": ComponentName.COAL,
    "sulfur": ComponentName.SULFUR,
    "oreGold": ComponentName.CATERIUM_ORE,
    "oreBauxite": ComponentName.BAUXITE_ORE,
    "oreUranium": ComponentName.URANIUM_ORE,
    "water": ComponentName.WATER,
    "liquidOil": ComponentName.OIL,
    "nitrogenGas": ComponentName.NITROGEN,
    "genericBiomass": ComponentName.BIOMASS,
    "wood": ComponentName.WOOD,
    "quartzCrystal": ComponentName.QUARTZ_CRYSTAL,
    "ironIngot": ComponentName.IRON_INGOT,
    "circuitBoardHighSpeed": ComponentName.AI_LIMITER,
    "aluminumPlate": ComponentName.ALCLAD_ALUMINUM_SHEET,
    "aluminumCasing": ComponentName.ALUMINUM_CASING,
    "aluminumIngot": ComponentName.ALUMINUM_INGOT,
    "aluminumScrap": ComponentName.ALUMINUM_SCRAP,
    "aluminaSolution": ComponentName.ALUMINA_SOLUTION,
    "battery": ComponentName.BATTERY,
    "gunpowder": ComponentName.BLACK_POWDER,
    "cable": ComponentName.CABLE,
    "circuitBoard": ComponentName.CIRCUIT_BOARD,
    "compactedCoal": ComponentName.COMPACTED_COAL,
    "computer": ComponentName.COMPUTER,
    "cement": ComponentName.CONCRETE,
    "coolingSystem": ComponentName.COOLING_SYSTEM,
    "copperDust": ComponentName.COPPER_POWDER,
    "copperIngot": ComponentName.COPPER_INGOT,
    "copperSheet": ComponentName.COPPER_SHEET,
    "crystalOscillator": ComponentName.CRYSTAL_OSCILLATOR,
    "electromagneticControlRod": ComponentName.ELECTROMAGNETIC_CONTROL_ROD,
    "steelPlateReinforced": ComponentName.ENCASED_INDUSTRIAL_BEAM,
    "plutoniumCell": ComponentName.ENCASED_PLUTONIUM_CELL,
    "uraniumCell": ComponentName.ENCASED_URANIUM_CELL,
    "fabric": ComponentName.FABRIC,
    "liquidFuel": ComponentName.FUEL,
    "modularFrameFused": ComponentName.FUSED_MODULAR_FRAME,
    "aluminumPlateReinforced": ComponentName.HEAT_SINK,
    "modularFrameHeavy": ComponentName.HEAVY_MODULAR_FRAME,
    "heavyOilResidue": ComponentName.HEAVY_OIL_RESIDUE,
    "highSpeedConnector": ComponentName.HIGH_SPEED_CONNECTOR,
    "ironPlate": ComponentName.IRON_PLATE,
    "ironRod": ComponentName.IRON_ROD,
    "modularFrame": ComponentName.MODULAR_FRAME,
    "motor": ComponentName.MOTOR,
    "nitricAcid": ComponentName.NITRIC_ACID,
    "nonFissibleUranium": ComponentName.NON_FISSILE_URANIUM,
    "nuclearWaste": ComponentName.URANIUM_WASTE,
    "petroleumCoke": ComponentName.PETROLEUM_COKE,
    "plastic": ComponentName.PLASTIC,
    "plutoniumFuelRod": ComponentName.PLUTONIUM_FUEL_ROD,
    "plutoniumPellet": ComponentName.PLUTONIUM_PELLET,
    "pressureConversionCube": ComponentName.PRESSURE_CONVERSION_CUBE,
    "polymerResin": ComponentName.POLYMER_RESIN,
    "highSpeedWire": ComponentName.QUICKWIRE,
    "ironPlateReinforced": ComponentName.REINFORCED_IRON_PLATE,
    "modularFrameLightweight": ComponentName.RADIO_CONTROL_UNIT,
    "rotor": ComponentName.ROTOR,
    "rubber": ComponentName.RUBBER,
    "ironScrew": ComponentName.SCREWS,
    "silica": ComponentName.SILICA,
    "stator": ComponentName.STATOR,
    "steelPlate": ComponentName.STEEL_BEAM,
    "steelPipe": ComponentName.STEEL_PIPE,
    "sulfuricAcid": ComponentName.SULFURIC_ACID,
    "computerSuper": ComponentName.SUPERCOMPUTER,
    "liquidTurboFuel": ComponentName.TURBO_FUEL,
    "motorLightweight": ComponentName.TURBO_MOTOR,
    "nuclearFuelRod": ComponentName.URANIUM_FUEL_ROD,
    "nuclearWaste": ComponentName.URANIUM_WASTE,
    "plutoniumWaste": ComponentName.PLUTONIUM_WASTE,
    "wire": ComponentName.WIRE,
    "spaceElevatorPart1": ComponentName.SMART_PLATING,
    "spaceElevatorPart2": ComponentName.VERSATILE_FRAMEWORK,
    "spaceElevatorPart3": ComponentName.AUTOMATED_WIRING,
    "spaceElevatorPart4": ComponentName.MODULAR_ENGINE,
    "spaceElevatorPart5": ComponentName.ADAPTIVE_CONTROL_UNIT,
    "spaceElevatorPart6": ComponentName.MAGNETIC_FIELD_GENERATOR,
    "spaceElevatorPart7": ComponentName.ASSEMBLY_DIRECTOR_SYSTEM,
    "spaceElevatorPart8": ComponentName.THERMAL_PROPULSION_ROCKET,
    "spaceElevatorPart9": ComponentName.NUCLEAR_PASTA,
    "mycelia": ComponentName.MYCELIA,
    "leaves": ComponentName.LEAVES,
    "flowerPetals": ComponentName.FLOWER_PETALS,
    "colorCartridge": ComponentName.COLOR_CARTRIDGE,
    "packagedNitrogenGas": ComponentName.PACKAGED_NITROGEN_GAS,
    "hazmatFilter": ComponentName.IODINE_INFUSED_FILTER,
    "filter": ComponentName.GAS_FILTER,
    "gasTank": ComponentName.EMPTY_TANK,
    "fluidCanister": ComponentName.EMPTY_CANISTER,
    "liquidBiofuel": ComponentName.LIQUID_BIOFUEL,
    "biofuel": ComponentName.SOLID_BIOFUEL,
}
